### ISSUE TITLE
id field is not of type string for model instead of ID

### ISSUE THREAD

**Issue by djom202** [aws-amplify/amplify-category-api#3044]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.12.0

### Amplify CLI Version

12.13.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

My schema has at least 30 days deployed without changes, today I going to change something however when I pushed the changes I got this issue:

```graphql
InvalidDirectiveError: geofenceVehicleId field is not of type String
```

Schema line before the change:
```graphql
geofenceVehicleId: ID! @index(name: "byGeofence", sortKeyFields: ["name"])
```

So I revert the change in my Schema but I'm still getting the same issue, after that I decided to change the type of the `geofenceVehicleId` for String, therefor I got the next error message:

```graphql
InvalidDirectiveError: id field is not of type String
```

My Schema in this moment:

```graphql
type Vehicle @model @auth(rules: [{ allow: public }]) {
  id: ID!
}
 ```
 
 I tried to change `ID` for `String` type and I can pushed the changes in a No-Prod environment and however I got this warning message:
 
 ```graphql
This update will replace table(s) [VehicleTable]
ALL EXISTING DATA IN THESE TABLES WILL BE LOST!
If this is intended, rerun the command with '--allow-destructive-graphql-schema-updates'.
```

for that reason I cannot push the changes into my prod environment and I had to rollback all changes, and I still not have idea the reason why I got this error message.

I also want to highlight that this is the only one that gives me this error, while the other relationships are the same but do not have this particular issue.

### Expected behavior

From my perspective, the schema should work as it did initially since I haven’t changed anything. However, I understand that a CLI update might have introduced changes, causing a new error like this. Ideally, the CLI should indicate what exactly I need to modify in my schema, specifying the exact line. Currently, it only mentions the attribute, and since I have many attributes with the same name, it’s difficult to pinpoint where the issue lies.

### Reproduction steps

I suppose that the steps are related to the way how I setup the schema.

### Project Identifier

Project Identifier: fb5b99268af59802a9999a876ab703cd

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by djom202** [comment]
Hi @AnilMaktala the points was that I not change anything, I pushed the some new changes when I got the error message, after that I rollback this changes but the error messages doesn't disappear, since it't not related to the change. for this I think it could be a new check into the CLI.

**Comment by bobbyu99** [comment]
Hi @djom202, It seems like you pushed some changes, then you see the following error. After rolling back those changes, the following error still exists, is that correct? If so, could you share with us what's the changes that make the error first appear so we could have a bit more context?
```
InvalidDirectiveError: geofenceVehicleId field is not of type String
```

**Comment by djom202** [comment]
Yeah sure, I changed this:

```
type Vehicle @model @auth(rules: [{ allow: public }]) {
  id: ID!
  model_year: String!
....
 }
```
by this:
```
type Vehicle @model @auth(rules: [{ allow: public }]) {
  id: ID!
  modelYear: String!
....
 }
```

**Comment by bobbyu99** [comment]
This error seems to be part of the validation for `@belongsTo @hasMany @hasOne` directives. Do you have any field that uses any of these directives?
```
InvalidDirectiveError: geofenceVehicleId field is not of type String
```

**Comment by bobbyu99** [comment]
I am working to repro this issue, could you share with us which CLI version you were using when your schema was deployed successfully 30 days ago?

**Comment by djom202** [comment]
I'm working in a Schema that I can share with You as public. And also I'm not sure if I can get the version i'm these moment however let me check.

**Comment by bobbyu99** [comment]
Thanks. Do you have a rough date of when your schema was deployed successfully last time so I could narrow down the changes we made?

**Comment by bobbyu99** [comment]
I noticed that `Vehicle` uses `plate` (a `String`) as its primary key, not `id`. `Geofence` references `Vehicle` through `geofenceVehicleId`, which is of type `ID!`. The types (`String` vs. `ID`) don't match, thus causing the error: 
```
InvalidDirectiveError: geofenceVehicleId field is not of type String
```

After setting `id` as the primary key in `Vehicle`, I am able to `amplify push` successfully.

**Comment by djom202** [comment]
Ok it make senses. however I change the plate for ID I'm not sure if still can use the same values there, so what I'd like to know if it's possible to any KEY to be unique the PLATE field instead of primary key?
?

**Comment by bobbyu99** [comment]
Sorry I am not sure I am following. Are you asking if it's possible to enforce uniqueness on a field like `plate` without making it the primary key?

**Comment by djom202** [comment]
> Sorry I am not sure I am following. Are you asking if it's possible to enforce uniqueness on a field like `plate` without making it the primary key?

Yes

**Comment by bobbyu99** [comment]
Unfortunately, we do not have any directive that enforces uniqueness at this moment.
