### ISSUE TITLE
ID field gets generated for models containing a compound primary key

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-category-api#584]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify CLI Version

8.5.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

None

### Amplify Categories

api

### Amplify Commands

Not applicable

### Describe the bug

According to doc https://docs.amplify.aws/cli/graphql/data-modeling/#configure-a-primary-key
`In the example below, todoId is the database’s primary key and an id field will no longer be created automatically anymore by the @model directive.`

Currently, observing the id field being generated when using a compound key.
![image](https://user-images.githubusercontent.com/87995712/175113270-4f374034-7861-4ae0-a732-7f6327d21d66.png)

The issue appears to be related to https://github.com/aws-amplify/amplify-cli/issues/9402 and a PR has been pushed.

Note: Datastore is not being used

### Expected behavior

When using compound key, ID field should not be generated.

### Reproduction steps

1. create graphql API
2. paste the schema provided
3. amplify push
4. do a create query on console and check DynamoDB

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type prodord @model @auth(rules: [{ allow: private }]) {
  pord_pk: String! @primaryKey(sortKeyFields: ["pord_sk"])
  pord_sk: String!
    @index(
      name: "listOrderItemsIndex"
      queryField: "itemsInOrder"
      sortKeyFields: ["pord_pk"]
    )
  type: String!
    @index(
      name: "typeIndex"
      queryField: "listItemsByType"
      sortKeyFields: ["type_sk"]
    )
  userOrProduct: String
    @index(name: "productOrUserIndex", queryField: "userOrProduct")
  type_sk: String!
  fname: String
  lname: String
  email: String
  avatar: String
  company: String
  name: String
  unitPrice: Int
  quantity: Int
}

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by mewtlu** [comment]
Thanks for reporting this ykethan, just wanted to add that unlike https://github.com/aws-amplify/amplify-cli/issues/9402 this issue is occurring for all models, even those beginning with an uppercase character (eg `CompanyUser`)

**Comment by alharris-at** [comment]
Hi, this issue should be resolved with the release of custom primary key. Could you confirm in your `amplify/cli.json` if `respectPrimaryKeyAttributesOnConnectionField` is set to `true`?

**Comment by muvashi** [comment]
Hi alharris-at, The field `respectPrimaryKeyAttributesOnConnectionField` is set to `true` in `amplify/cli.json` and the behaviour still persists.

Please find below the sample schema used at my end : -

```
type Movie @model @auth(rules: [{ allow: public}]) 
 { 
    imdb: ID! @primaryKey 
    title: String! 
    status: String! 
    rating: Int! 
    description: String 
}
```

On creating the createMovie mutation, id field is generated in the DynamoDB table. On checking the resolver, I found that id field is generated and set under ctx.

**Comment by rashmibcyberdive** [comment]
Hi @alharris-at 
I can confirm the same behavior as mentioned above using the same model and found id column being generated in the DynamoDB table.
